version: '3'

services:
  traefik:
    image: traefik:latest
    container_name: traefik
    restart: unless-stopped
    security_opt:
      - no-new-privileges:true
    networks:
      - proxy
    ports:
      - 80:80
      - 443:443
    environment:
      - CF_API_EMAIL=${CF_API_EMAIL}
      - CF_DNS_API_TOKEN=${CF_DNS_API_TOKEN}
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - ./traefik.yml:/traefik.yml:ro
      - ./traefik_services.yml:/traefik_services.yml:ro
      - ./acme.json:/acme.json
    labels:
      - "traefik.http.routers.api.entrypoints=https"
      - "traefik.http.routers.api.rule=Host(`traefik.local.joaopereira.ie`)"
      - "traefik.http.routers.api.service=api@internal"
      - "traefik.http.routers.api.middlewares=apiSimpleAuth"
      - "traefik.http.middlewares.apiSimpleAuth.basicauth.users=joaoseph:$$apr1$$95ido6YT$$.2pv3uw4P4539GXldGMm1"

networks:
  proxy:
    external: true
