api:
  dashboard: true

    # accessLog: {}
log:
  level: DEBUG

entryPoints:
  http:
    address: ":80"
    http:
      redirections:
        entryPoint:
          to: "https"
          scheme: "https"
          permanent: true
  https:
    address: ":443"
    http:
      tls:
        certResolver: cloudflare
        domains:
          - main: "joaopereira.ie"
            sans: "*.joaopereira.ie"
          - main: "local.joaopereira.ie"
            sans: "*.local.joaopereira.ie"

certificatesResolvers:
  cloudflare:
    acme:
      storage: "acme.json"
      dnsChallenge:
        provider: "cloudflare"
        delayBeforeCheck: 60
        disablePropagationCheck: true
        resolvers:
          - "1.1.1.1:53"

providers:
  docker:
    watch: true
    network: "proxy"
    exposedbydefault: false
    endpoint: "unix:///var/run/docker.sock"
  file:
    filename: "traefik_dynamic.yml"

