services:
  nextcloud:
    image: nextcloud:latest
    container_name: nextcloud
    restart: unless-stopped
    depends_on:
      - db
      - redis
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - MYSQL_USER=nextcloud
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_HOST=nextcloud-db
      - APACHE_DISABLE_REWRITE_IP=1
      - NEXTCLOUD_TRUSTED_DOMAINS=nextcloud.local.joaopereira.ie,nextcloud.joaopereira.ie
      - TRUSTED_PROXIES=traefik
      - OVERWRITEPROTOCOL=https
      - REDIS_HOST=nextcloud-redis
    volumes:
      - /mnt/drive/config/nextcloud:/var/www/html
      - /mnt/drive/data/nextcloud:/var/www/html/data
    networks:
      - internal
      - proxy
    labels:
      # Enable Traefik for Nextcloud
      - "traefik.enable=true"
      
      # HTTP Routers
      - "traefik.http.routers.nextcloud.entrypoints=https"
      - "traefik.http.routers.nextcloud.rule=Host(`nextcloud.joaopereira.ie`) || Host(`nextcloud.local.joaopereira.ie`)"
      - "traefik.http.routers.nextcloud.tls=true"
      - "traefik.http.routers.nextcloud.tls.certresolver=cloudflare"

      # Service configuration
      - "traefik.http.services.nextcloud.loadbalancer.server.port=80"

      # Middleware for redirecting well-known CalDAV/CardDAV requests
      - "traefik.http.middlewares.nextcloud-dav.redirectregex.regex=^https://(.*)/.well-known/(card|cal)dav"
      - "traefik.http.middlewares.nextcloud-dav.redirectregex.replacement=https://$$1/remote.php/dav/"
      - "traefik.http.middlewares.nextcloud-dav.redirectregex.permanent=true"

      # Security headers middleware
      - "traefik.http.middlewares.nextcloud-headers.headers.referrerPolicy=no-referrer"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsSeconds=31536000"
      - "traefik.http.middlewares.nextcloud-headers.headers.forceSTSHeader=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsPreload=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.stsIncludeSubdomains=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.browserXssFilter=true"
      - "traefik.http.middlewares.nextcloud-headers.headers.customRequestHeaders.X-Forwarded-Proto=https"

      # Link middleware to router
      - "traefik.http.routers.nextcloud.middlewares=nextcloud-dav,nextcloud-headers"

  db:
    image: mariadb:10.5
    container_name: nextcloud-db
    restart: unless-stopped
    command: --transaction-isolation=READ-COMMITTED --binlog-format=ROW
    volumes:
      - db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
      - MYSQL_DATABASE=nextcloud
      - MYSQL_USER=nextcloud
    networks:
      - internal

  redis:
    image: redis:alpine
    container_name: nextcloud-redis
    restart: unless-stopped
    volumes:
      - redis:/data
    networks:
      - internal

volumes:
  db:
    driver: local
  redis:
    driver: local

networks:
  internal:
  proxy:
    external: true

