services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/jellyfin/tvseries:/data/tvshows
      - /srv/jellyfin/movies:/data/movies
    ports:
      - 8096:8096
      - 8920:8920 # Optional for HTTPS
      - 7359:7359/udp # Optional
      - 1900:1900/udp # Optional
    restart: unless-stopped
    networks:
      - internal
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.local.joaopereira.ie`)"
      # - "traefik.http.routers.jellyfin.middlewares=jellyfin-headers"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

networks:
  internal:
  proxy:
    external: true

