services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - UMASK=002
    volumes:
      - /srv/jellyfin/config:/config
      - /srv/data/media/:/data/media/
    restart: unless-stopped
    networks:
      - proxy
    devices: 
      - /dev/dri:/dev/dri
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyfin.entrypoints=https"
      - "traefik.http.routers.jellyfin.rule=Host(`jellyfin.joaopereira.ie`) || Host(`jellyfin.local.joaopereira.ie`)"
      - "traefik.http.services.jellyfin.loadbalancer.server.port=8096"

  transmission:
    image: haugene/transmission-openvpn
    container_name: transmission
    cap_add:
      - NET_ADMIN
    volumes:
      - /srv/transmission/config:/config
      - /srv/data/torrents:/data
    environment:
      - OPENVPN_PROVIDER=NORDVPN
      - OPENVPN_USERNAME=${OPENVPN_USERNAME}
      - OPENVPN_PASSWORD=${OPENVPN_PASSWORD}
      - NORDVPN_COUNTRY=DE
      - NORDVPN_CATEGORY=legacy_p2p
      - NORDVPN_PROTOCOL=tcp
      - NORDVPN_SERVER=sg460.nordvpn.com
      - LOCAL_NETWORK=192.168.1.0/24,172.19.0.0/24
      - PUID=1000
      - PGID=1000
      - TRANSMISSION_WEB_UI=flood-for-transmission
    ports:
      - 9091:9091
      - 51413:51413
      - 51413:51413/udp
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.transmission.entrypoints=https"
      - "traefik.http.routers.transmission.rule=Host(`transmission.local.joaopereira.ie`)"
      - "traefik.http.services.transmission.loadbalancer.server.port=9091"

  radarr:
    image: ghcr.io/hotio/radarr
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - UMASK=002
    volumes:
      - /srv/radarr/config:/config
      - /srv/data:/data
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.radarr.entrypoints=https"
      - "traefik.http.routers.radarr.rule=Host(`radarr.local.joaopereira.ie`)"
      - "traefik.http.services.radarr.loadbalancer.server.port=7878"

  sonarr:
    image: ghcr.io/hotio/sonarr
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - UMASK=002
    volumes:
      - /srv/sonarr/config:/config
      - /srv/data:/data
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.sonarr.entrypoints=https"
      - "traefik.http.routers.sonarr.rule=Host(`sonarr.local.joaopereira.ie`)"
      - "traefik.http.services.sonarr.loadbalancer.server.port=8989"

  prowlarr:
    image: ghcr.io/hotio/prowlarr
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - UMASK=002
    volumes:
      - /srv/prowlarr/config:/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.prowlarr.entrypoints=https"
      - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.local.joaopereira.ie`)"
      - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"

  jellyseerr:
    image: ghcr.io/hotio/jellyseerr
    container_name: jellyseerr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Dublin
      - UMASK=002
    volumes:
      - /srv/jellyseerr/config:/config
    restart: unless-stopped
    networks:
      - proxy
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.jellyseerr.entrypoints=https"
      - "traefik.http.routers.jellyseerr.rule=Host(`jellyseerr.joaopereira.ie`) || Host(`jellyseerr.local.joaopereira.`)"
      - "traefik.http.services.jellyseerr.loadbalancer.server.port=5055"

  flaresolverr:
    image: ghcr.io/flaresolverr/flaresolverr:latest
    container_name: flaresolverr
    environment:
      - LOG_LEVEL=${LOG_LEVEL:-info}
      - LOG_HTML=${LOG_HTML:-false}
      - CAPTCHA_SOLVER=${CAPTCHA_SOLVER:-none}
      - TZ=Europe/London
    ports:
      - "${PORT:-8191}:8191"
    restart: unless-stopped
    networks: 
    - proxy

networks:
  proxy:
    external: true

